-- phpMyAdmin SQL Dump
-- version 5.0.2
-- https://www.phpmyadmin.net/
--
-- Hôte : 127.0.0.1:3306
-- Généré le : lun. 18 avr. 2022 à 15:50
-- Version du serveur :  5.7.31
-- Version de PHP : 7.3.21

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données : `autocompletion`
--

-- --------------------------------------------------------

--
-- Structure de la table `jeux`
--

DROP TABLE IF EXISTS `jeux`;
CREATE TABLE IF NOT EXISTS `jeux` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nom` varchar(255) NOT NULL,
  `prix` float NOT NULL,
  `description` varchar(2000) NOT NULL,
  `date` date NOT NULL,
  `avis` float NOT NULL,
  `plateforme` varchar(300) NOT NULL,
  `image` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=47 DEFAULT CHARSET=utf8;

--
-- Déchargement des données de la table `jeux`
--

INSERT INTO `jeux` (`id`, `nom`, `prix`, `description`, `date`, `avis`, `plateforme`, `image`) VALUES
(1, 'Far Cry 6', 69.99, 'Far Cry 6 est un FPS qui se déroule sur l\'île tropicale fictive de Yara. Vous incarnez Dani Rojas, un membre de la guérilla locale qui lutte contre le régime oppressif du dictateur du pays, Anton Castillo, qui prépare son fils à prendre sa suite. Pour vous aider dans votre combat, vous pouvez compter sur vos alliés les Amigos et fabriquer vos propres armes et véhicules.', '2021-10-07', 8.7, 'PS5, PS4, PC, Xbox', 'farcry6.png'),
(2, 'God of War', 53.95, 'Trame. Kratos est de retour avec son fils Atreus pour de nouvelles aventures. Après avoir sauvé Midgard des Valkyries, ils doivent parcourir les Neufs Mondes de l\'Yggdrasil pour tenter de sauver l\'existence du Ragnarok, la fin du monde.', '2022-01-14', 8.9, 'PS5, PS4, PC, Xbox', 'godofwar.jpg'),
(3, 'Lost Ark', 19.99, 'Lost Ark est un hack\'n slash sur PC en vue isométrique dans lequel vous pouvez incarnez 18 personnages jouables. Contrairement aux canons du genre, le jeu prend place au sein d\'un monde ouvert multijoueur en ligne. Des montures sont également à votre disposition afin de vous assister en combat.', '2022-02-11', 8.4, 'PC', 'Lostark.jpg'),
(4, 'Total War: Warhammer III', 28.49, 'Total War : WARHAMMER III pour PC est un jeu vidéo de stratégie au tour par tour et en temps réel, basé sur le jeu de table du même nom, et le troisième de la série de jeux vidéo. Les joueurs déplacent à tour de rôle leurs pièces/personnages sur la carte et apprennent à gérer au mieux leurs colonies afin d\'atteindre tous leurs objectifs, de vaincre leurs ennemis et de s\'entendre avec ceux qu\'ils ne peuvent pas vaincre immédiatement !', '2022-02-17', 8.6, 'PC', 'totalwar.jpg'),
(5, 'Gran Turismo 7', 69.99, 'Gran Turismo 7 est un jeu de simulation automobile sur PlayStation 5 développé par Polyphony Digital et édité par Sony Interactive Entertainment. Il s\'agit du huitième volet principal de la saga de Playstation.', '2022-03-04', 7.8, 'PS5, PS4', 'gt7.jpg'),
(6, 'Assassin’s Creed Valhalla : Dawn of Ragnarök', 39.99, 'Dans Assassin\'s Creed Valhalla : L\'Aube du Ragnarök, l\'extension la plus ambitieuse de l\'histoire de la franchise, Eivor devra faire face à son destin sous les traits d\'Odin, le dieu nordique de la guerre et de la sagesse. Libérez vos nouveaux pouvoirs divins dans une quête désespérée au travers d\'un monde époustouflant. Poursuivez votre saga viking légendaire et sauvez votre fils du destin.', '2022-04-10', 8.6, 'PS5, PS4, PC, Xbox', 'assasinscreed.png'),
(7, 'Marvel’s Avengers', 15, 'Marvel\'s Avengers est un jeu d\'action-aventure épique qui allie une histoire cinématographique et des modes solo et coop, offrant l\'expérience de jeu Avengers ultime. Formez des équipes en ligne allant jusqu\'à quatre joueurs, maîtrisez d\'incroyables capacités, personnalisez votre équipe de héros qui grandira au fil du temps et défendez la Terre contre des menaces toujours plus terribles. Marvel\'s Avengers débute lors du A-Day, où Captain America, Iron Man, Hulk, Black Widow et Thor célèbrent l\'inauguration d\'un nouveau quartier général des Avengers à San Francisco et le lancement de leur héliporteur alimenté par une source d\'énergie expérimentale. Cependant, la journée vire au cauchemar lorsqu\'un accident catastrophique entraîne la destruction d\'une grande partie de la ville. Les Avengers sont considérés responsables de la tragédie et se séparent.', '2021-03-18', 7.4, 'PC, Xbox', 'marvek.jpg'),
(8, 'Resident Evil Village', 21.99, 'Resident Evil Village est un survival-horror. Se déroulant quelques années après Resident Evil 7 Biohazard, il met en scène Ethan Winters, sa femme Mia et Chris Redfield, le héros légendaire de la série Resident Evil. L\'action est en vue à la première personne et le joueur incarne un Ethan désemparé et brisé qui se retrouve confronté à des monstruosités dans un village.', '2021-05-07', 7.9, 'PS4, PC, Xbox', 'residentevil.png'),
(9, 'Donjons & Dragons : Dark Alliance ', 14.99, 'Donjons & Dragons : Dark Alliance est un jeu développé par Tuque Games et édité Wizards of the Coast. Hack\'n\'Slash coopératif jusqu\'à quatre joueurs, le titre prend place dans la région glacière d\'Icewind Dale', '2021-06-22', 7.8, 'PC', 'dugeon.jpg'),
(10, 'Madden NFL 22', 69.99, 'Le tout nouveau Dynamic Gameday présent dans tous les modes de jeu de Madden NFL 22 vous apporte tout ce que vous aimez dans la NFL. \r\n\r\nLe Dynamic Gameday est partout dans Madden NFL 22, que ce soit dans la planification d\'un match dans le mode Franchise remanié, en entrant directement dans la mêlée avec Play Now ou en jouant en ligne avec Madden Ultimate Team.', '2021-08-20', 8.4, 'PS5, PS4, PC, Xbox', 'nfl.jpg'),
(11, 'NBA 2K22', 23.99, 'NBA 2K22 est une simulation de basket-ball éditée par 2K Games et développée par Visual Concepts. Le jeu permet une immersion complète au sein de la NBA et, plus généralement, dans le monde professionnel du basket avec toutes les équipes et joueurs qui composeront la saison 2021-2022.', '2021-09-10', 8.6, 'PS5, PS4, PC, Xbox', 'nba.pg.jpg'),
(12, 'FIFA 22', 44.99, 'FIFA 22 est une simulation de football éditée par Electronic Arts. Comme chaque saison, le jeu offre son lot d\'améliorations techniques pour toujours plus de réalisme ainsi que des animations et des comportements toujours plus poussés. Les modes carrière et Ultimate Team disposent également de nouveaux ajouts.', '2021-09-27', 8.4, 'PS5, PS4, PC, Xbox', 'FIFA-22.jpg'),
(13, 'Age of Empire IV', 40.99, 'Age of Empires IV sur PC est un jeu de stratégie qui appartient à la célèbre saga de stratégie. Il vous sera possible de prendre part à des batailles historiques avec des armées possédant leurs propres caractéristiques.', '2021-10-08', 8.3, 'PS5, PC', 'ageempire.jpg'),
(14, 'Mario Party Superstars ', 43.99, 'Mario Party Superstars est un party-game qui porte bien son nom, puisqu\'il réunit plus d\'une centaine de mini-jeux issus de tous les épisodes de la série, dont la Nintendo 64 ! Le titre est jouable seul ou bien en multijoueur local et en ligne.', '2021-10-28', 8.6, 'PS5, PS4, PC, Xbox', 'mariosuperstar.jpg'),
(15, 'Call of Duty : Vanguard ', 69.99, 'Call of Duty : Vanguard est le dernier ajout de la célèbre licence de jeux de tirs, Call of Duty. Celui-ci nous plonge au coeur des affrontements de la Seconde Guerre mondiale, et particulièrement ceux ayant lieu en Europe et dans le Pacifique.', '2021-11-05', 7.9, 'PS5, PS4, PC, Xbox', 'vanguard.jpg'),
(16, 'Pokémon Diamant Étincelant ', 34.99, 'Pokémon Diamant Étincelant / Perle Scintillante est un remake de Pokémon Version Diamant / Perle sorti sur Nintendo DS. Avec un nouveau style graphique plutôt enfantin, les joueurs peuvent découvrir ou redécouvrir la région de Sinnoh et retrouver les Pokémons de la quatrième génération.', '2021-10-19', 7.8, 'PC, SWITCH', 'diamannt.jpg'),
(17, 'Diablo II: Resurrected ', 39.99, 'Diablo II : Resurrected est la remasterisation du hack\'n\'slash culte Diablo II et de son extension Lord of Destruction. Cette version remise aux goûts présente de nouveaux graphismes ultra détaillés, des cinématiques retravaillées et une bande son améliorée, tandis que le gameplay et les systèmes du jeu d’origine sont identiques à ceux de l’époque.', '2021-09-24', 8.5, 'PS5, PS4, PC', 'diabloII.jpg'),
(18, 'Battlefield 2042 ', 29.99, 'Battlefield 2042 est un jeu de tir à la première personne multijoueur ancré dans un futur dystopique. Deux nations mènent une guerre totale, les Etats-Unis et la Russie. Trois modes de jeux sont proposés : All-Out Warfare (128 joueurs sur PS5/Xbox Series, 64 sur PS4/Xbox One), Hazard Zone et Mode Portal.', '2021-10-19', 8.2, 'PS5, PS4, PC, Xbox', '2042'),
(19, 'Dying Light 2 : Stay Human', 48.99, 'Dying Light 2 est un Survival-Horror dans lequel le joueur doit survivre dans un environnement peuplé de zombies. Dans ce nouvel opus, l\'enjeu sera de contrôler notamment des réserves d\'eau et de nourriture afin de maîtriser une cité de survivants. Les choix du joueur ont ainsi une importance capitale dans le déroulement du scénario.', '2022-02-04', 8.5, 'PS5, PS4, PC, Xbox', 'dying.jpg'),
(20, 'Star Wars: The Old Republic – Legacy of the Sith ', 39.99, 'Legacy of the Sith est la mise à jour 7.0 du MMORPG Star Wars : The Old Republic. Celle-ci entraîne les joueurs dans une campagne militaire visant à s\'emparer d\'une planète vitale pour leur faction afin de découvrir le plan ultime du renégat Sith, Dark Malgus. De nouvelles zones sont au rendez-vous et le niveau maximal atteignable passe à 80.', '2022-02-15', 9, 'PC, XBOX', 'starwars.jpg'),
(21, 'Dragon Ball Z : Kakarot', 29.99, 'Dragon Ball Z Kakarot permet de revivre l\'histoire de Dragon Ball Z dans le peau de Kakarot / Goku. Développé par CyberConnect2, le jeu reproduit les moments emblématiques de l\'oeuvre originale. Il est possible de voler dans un monde vaste que vous débloquerez en progressant dans l\'aventure, de croiser des ennemis, d\'accepter des quêtes, ou encore de pêcher.', '2020-01-17', 9.1, 'PC, PS4, Xbox One', 'dbzkakarot.jpg'),
(22, 'Cyberpunk 2077', 29.99, 'Cyberpunk 2077 est un jeu de rôle futuriste et dystopique inspiré du jeu de rôle papier du même nom. Dans un monde devenu indissociable de la cybernétique, l\'indépendance des robots humanoïdes pose quelques problèmes...', '2020-05-16', 7.9, 'PC, PS4, Xbox One', 'cyberpunk.jpg'),
(23, 'The Last of Us Part 2', 19.99, 'Au centre de l\'intrigue du premier volet, nous retrouvons à nouveau Joel et Ellie plus déterminés que jamais à éradiquer les infectés jusqu\'au dernier. Se déroulant à nouveau dans un monde post apocalyptique, le duo toujours aussi soudé devra prendre les décisions qui s\'imposent afin de survivre un seul jour de plus à cette pandémie.', '2020-05-29', 9.7, 'PS4', 'lastofusII.jpg'),
(24, 'Ghost of Tsushima ', 29.99, 'Ghost of Tsushima est un jeu d\'action qui prend place au Japon dans lequel les développeurs ont mis les détails au centre du jeu afin qu\'il respecte l\'Histoire du pays. Le monde étant totalement ouvert, le joueur pourra s\'y balader afin de découvrir ce pays d\'antan.', '2020-06-26', 8.4, 'PS4', 'ghost.jpg'),
(25, 'Watch Dogs Legion', 14.99, 'Watch Dogs Legion, troisième épisode de la série d\'Ubisoft, vous plonge dans le Londres post-Brexit ultra-connecté et surveillé. Vous aurez la possibilité d\'hacker n\'importe qui, mais aussi d\'en prendre possession. Chaque mort est permanente, d\'où l\'utilité de prendre possession des PNJ.', '2020-10-29', 7.8, 'PC, PS4, Xbox one', 'wdogs.jpg'),
(26, 'Trials Rising', 19.99, 'Cette nouvelle entrée dans la gamme Trials reprend les mécaniques habituelles de la série en mélangeant course et plateforme. Nouvelles pistes, nouveaux modes de jeu et nouveaux environnements sont à l\'ordre du jour, avec une dimension multijoueur plus développée.', '2019-02-28', 8.3, 'PS4, PC, Xbox One', 'trial.jpg'),
(27, 'The Legend of Zelda : Link\'s Awakening', 44.99, 'The Legend of Zelda : Link\'s Awakening (2019) est un remake de l\'épisode culte de la saga paru en 1993 sur Game Boy. Il est cette fois-ci question d\'une refonte totale du quatrième opus de la série, dans lequel nous suivons Link, échoué sur l\'île mystérieuse de Cocolint.', '2019-09-20', 8.6, 'SWITCH', 'zeldalink.jpg'),
(28, 'Devil May Cry 5 ', 12.99, 'Devil May Cry 5 est la nouvelle itération de la célèbre franchise de Capcom qui prend place quelques années après les événements du quatrième opus et l\'incident de l\'Ordre de l\'Epée. Les forces du mal sont à leur apogée et un arbre maléfique trône en plein Red Grave City, ses racines s\'attaquant aux habitants.', '2019-02-08', 8.3, 'PC, PS4, ONE', 'devil.jpg\r\n'),
(29, 'Metro Exodus', 8.99, 'Metro Exodus est le troisième épisode de la franchise \"Metro\", une adaptation de l\'oeuvre littéraire écrite par Dmitri Glukhovski. Dans cet univers uchronique, la Russie n\'est plus d\'un champ de ruines après une guerre nucléaire. La survie est toujours au cœur d\'une expérience laissant le survivant explorer un monde post-apocalyptique. Artyom, le protagoniste de la série Metro, quitte les souterrains de Moscou avec d\'autres membres de l\'Ordre pour explorer l\'est de la Russie en quête d\'une nouvelle vie.', '2019-02-15', 8.3, 'PC', 'metro.jpg'),
(30, 'Star Wars Jedi : Fallen Order', 19, 'Jeu développé par Respawn Entertainment, Jedi Fallen Order installe son intrigue entre le troisième et le quatrième volet de la saga. Le joueur incarne un jeune Padawan cherchant à fuir l\'Empire et la traque des derniers Jedi encore en vie, une chasse à l\'homme menée par Darth Vader.', '2019-11-15', 8.5, 'PC, PS4, Xbox one', 'fallenorder.jpg'),
(31, 'Pokémon Épée / Bouclier', 33.99, 'Pokémon Épée / Bouclier est le nouvel épisode de la série Pokémon, exclusif à la console de salon de Nintendo. Le jeu prend place dans la nouvelle région de Galar et donne accès à trois nouveaux Pokémons de départ : Ouistempo (plante), Flambino (feu) et Larméléon (eau).', '2019-10-15', 7, 'Switch', 'epee.jpg'),
(32, 'Borderlands 3', 12.99, 'Borderlands 3 est un RPG en vue FPS. Contrairement aux épisodes précédents, les joueurs vont pouvoir visiter Prométhée. Cette planète est la zone où Atlas a découvert la première Arche, une des éléments importants de la série.', '2019-08-13', 8, 'PC, PS4, ONE', 'borderlands.jpg'),
(33, '\r\nRed Dead Redemption II ', 12.99, 'Suite du précédent volet multi récompensé, Red Dead Redemption II nous permet de nous replonger sur PS4 dans une ambiance western synonyme de vastes espaces sauvages et de villes malfamées. L\'histoire se déroule en 1899, avant le premier Red Dead Redemption, au moment où Arthur Morgan doit fuir avec sa bande à la suite d\'un braquage raté.', '2018-10-28', 9.3, 'PC, PS4, ONE', 'reddead.jpg'),
(34, 'Dark Souls: Remastered ', 29.99, 'Dark Souls Remastered sur PS4 est un jeu de rôle orienté action très difficile se déroulant dans un univers infesté de démons. Dans la peau d\'un mort-vivant, le joueur doit se battre contre de nombreux types d\'ennemis et de boss pour avoir une chance de retourner dans le monde des hommes. 10 classes de personnages et diverses techniques sont disponibles pour tenter de relever les défis extrêmement relevés qui se dressent à tout moment sur notre route en solo comme en multi.', '2018-05-18', 8.6, 'PC, Switch, PS4, Xbox one', 'souls.jpg'),
(35, 'Subnautica', 0, 'Subnautica est un jeu d\'aventure dans un monde ouvert sous-marin. Dans la peau d\'un scientifique échoué dans ce monde étranger situé sous l\'eau, vous allez devoir trouver comment survivre tout en faisant de nouvelles découvertes sur la nature de la faune locale.', '2018-01-23', 8.4, 'PC', 'sub.jpg'),
(36, 'Monster Hunter World', 14.99, 'La dernière entrée de la série Monster Hunter. Plus complet que jamais, le jeu transporte le joueur au travers de batailles contre de terribles monstres et de magnifiques paysages. Récupérerez des objets sur vos ennemis, créez de nouveaux équipements et armures, explorez tous les territoires disponibles. Saurez vous devenir le chasseur ultime ?', '2018-01-28', 8.4, 'PC, PS4, ONE', 'hunter.jpeg\r\n'),
(37, 'Forza Horizon 4', 34.99, 'Forza Horizon 4 est un jeu de course en monde ouvert développé par Playground Games. Il prend place dans le nord du Royaume-Uni où les quatre saisons s\'enchaînent dans un Monde Persistant (une saison = une semaine). Le jeu propose aussi bien des courses solo que des épreuves compétitives et collaboratives en ligne. Il contient 460 véhicules et des outils de création et de personnalisation.', '2018-10-02', 8.7, 'Xbox, PS4', 'forza.jpg'),
(38, 'Assassin\'s Creed Odyssey', 17.99, 'Assassin\'s Creed Odyssey est une nouvelle entrée dans la franchise qui se déroule avant Assassin\'s Creed Origins. il sera possible d\'y incarner le descendant de Leonidas de Sparte, garçon ou fille, dans la Grèce Antique. Au programme des nouveautés, un nouveau système de combat, des batailles rangées et un côté RPG encore plus poussé avec un système de dialogue à choix multiples.', '2018-10-05', 8.2, 'PS4, ONE', 'odyssey.jpg'),
(39, 'Assassin\'s Creed Odyssey', 17.99, 'Assassin\'s Creed Odyssey est une nouvelle entrée dans la franchise qui se déroule avant Assassin\'s Creed Origins. il sera possible d\'y incarner le descendant de Leonidas de Sparte, garçon ou fille, dans la Grèce Antique. Au programme des nouveautés, un nouveau système de combat, des batailles rangées et un côté RPG encore plus poussé avec un système de dialogue à choix multiples.', '2018-10-05', 8.2, 'PS4, ONE', 'odyssey.jpg'),
(40, 'Among Us', 20.99, 'Among Us est un party-game spatial jouable de 4 à 10 joueurs. Dans une station spatiale, il y a un imposteur caché parmi l\'équipage dont la mission est d\'assassiner les autres joueurs sans se faire prendre. Les parties et les avatars sont personnalisables et le jeu dispose de cross-platform avec les joueurs iOS et Android.', '2018-06-15', 7.8, 'PC, iOS, Android', 'us.jpg'),
(41, 'The Legend of Zelda: Breath of the Wild', 19.99, 'The Legend of Zelda : Breath of the Wild est un jeu d\'action/aventure. Link se réveille d\'un sommeil de 100 ans dans un royaume d\'Hyrule dévasté. Il lui faudra percer les mystères du passé et vaincre Ganon, le fléau. L\'aventure prend place dans un gigantesque monde ouvert et accorde ainsi une part importante à l\'exploration. Le titre a été pensé pour que le joueur puisse aller où il veut dès le début, s\'éloignant de la linéarité habituelle de la série.', '2017-03-03', 9, 'Switch', 'breath.jpg'),
(42, 'Mario Kart 8 Deluxe ', 24.99, 'Mario Kart 8 sur Switch est un jeu de course coloré et délirant qui reprend les personnages phares des grandes licences Nintendo. Le joueur peut y affronter ses amis dans différents modes et types de coupes et a accès à 32 circuits aux environnements variés. Il est possible de jouer jusqu\'à 12 simultanément en ligne et 4 en local.', '2017-04-27', 8.7, 'Switch', 'mario.jpg'),
(43, 'FIFA 21', 21.99, 'FIFA 21 est une simulation de football éditée par Electronic Arts. Comme chaque année, le jeu promet des améliorations techniques pour toujours plus de réalisme ainsi que des animations et des comportements toujours plus poussés. Les modes carrière et Ultimate Team disposent également de nouveaux ajouts.', '2020-09-09', 8.3, 'PC, PS4, PS5, Xbox one', 'fifa.jpg'),
(44, 'FIFA 20', 10.99, 'FIFA 20 est le nouveau titre de la série des FIFA, un jeu de simulation de football édité par Electronic Arts. La plus grande nouveauté de ce titre c\'est le retour du mode Volta autrefois appelé FIFA Street.', '2019-08-27', 7.9, 'PS4, Xbox one', 'fifa20.jpg'),
(45, 'NBA 2K21', 15.99, 'NBA 2K21 est une simulation de basket-ball éditée par 2K Games. Ce titre est la version 2021 de la franchise. Vous allez pouvoir jouer les meilleurs équipes et les meilleurs joueurs de NBA de la prochaine saison 2020-2021.', '2020-08-04', 7.3, 'PS4, PS5, Xbox one', '2K21.jpg'),
(46, 'NBA 2K20 ', 14, 'NBA 2K20 est une simulation de basket-ball édité par 2K Games. Ce titre est la version 2020 de la franchise. Vous allez pouvoir jouer les meilleurs équipes et les meilleurs joueurs de NBA de la prochaine saison 2019-2020.', '2019-08-06', 7.3, 'PC, PS4, Switch, Xbox one', '2K20');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
